### PR TITLE
Development

### PR DESCRIPTION
**Pull request by huzaifa26**

### CODE REVIEW

**Review by franciskouaho — APPROVED** [review]

**Comment by Itachi-Uchihaa** [comment]
@huzaifa26 Hello what i should put in the url slug  ?

**Comment by Itachi-Uchihaa** [comment]
@huzaifa26 I cant test it right now its normal ? because you didnt the display of menu right ?

**Comment by huzaifa26** [comment]
> @huzaifa26 Hello what i should put in the url slug ?

you can use this url for now. http://localhost:3000/surplace/123/123/123

**Comment by huzaifa26** [comment]
> @huzaifa26 I cant test it right now its normal ? because you didnt the display of menu right ?

If you open this url. You can view the menu. And you can also view sub menu of items which have options in it.

**Comment by Itachi-Uchihaa** [comment]
https://webappmcaisse.vercel.app/surplace/123/123/123


this is the url of preprod like this you can try it on live

**Comment by franciskouaho** [comment]
Good job @huzaifa26

**Comment by huzaifa26** [comment]
Okay great. Thank you

**Pull request merged**
